# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndemo.proto\x12\x04\x64\x65mo\"%\n\x15\x41\x63\x63umulatedElementDto\x12\x0c\n\x04item\x18\x01 \x01(\x05\"\x1e\n\x0cSumResultDto\x12\x0e\n\x06result\x18\x01 \x01(\x05\"&\n\x12SumArrayRequestDto\x12\x10\n\x08\x65lements\x18\x01 \x03(\x05\".\n\rSumRequestDto\x12\r\n\x05\x66irst\x18\x01 \x01(\x05\x12\x0e\n\x06second\x18\x02 \x01(\x05\x32\xbf\x02\n\x08MiniDemo\x12.\n\x03Sum\x12\x13.demo.SumRequestDto\x1a\x12.demo.SumResultDto\x12\x38\n\x08SumArray\x12\x18.demo.SumArrayRequestDto\x1a\x12.demo.SumResultDto\x12>\n\tSumStream\x12\x1b.demo.AccumulatedElementDto\x1a\x12.demo.SumResultDto(\x01\x12\x46\n\x14SumArrayDetailStream\x12\x18.demo.SumArrayRequestDto\x1a\x12.demo.SumResultDto0\x01\x12\x41\n\nAccumulate\x12\x1b.demo.AccumulatedElementDto\x1a\x12.demo.SumResultDto(\x01\x30\x01\x42\x07\xaa\x02\x04\x44\x65mob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'demo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\004Demo'
  _globals['_ACCUMULATEDELEMENTDTO']._serialized_start=20
  _globals['_ACCUMULATEDELEMENTDTO']._serialized_end=57
  _globals['_SUMRESULTDTO']._serialized_start=59
  _globals['_SUMRESULTDTO']._serialized_end=89
  _globals['_SUMARRAYREQUESTDTO']._serialized_start=91
  _globals['_SUMARRAYREQUESTDTO']._serialized_end=129
  _globals['_SUMREQUESTDTO']._serialized_start=131
  _globals['_SUMREQUESTDTO']._serialized_end=177
  _globals['_MINIDEMO']._serialized_start=180
  _globals['_MINIDEMO']._serialized_end=499
# @@protoc_insertion_point(module_scope)
